### ISSUE TITLE
Create a bucket list destination

### ISSUE THREAD

**Issue by dunkl1lm** [dunkl1lm/Planit_Earth#5]
### User Story
I would like to be able to search for a destination and add it to my bucket list.

### Acceptance Criteria
- [ ] begin typing a location and receive suggestions
- [ ] select a suggested location and add it my bucket list
- [ ] view the destination as a point on the bucket list map

### Task List
- [ ] mockup
- [ ] prototype
- [ ] database
- [ ] backend
- [ ] frontend
