### ISSUE TITLE
Convert a bucket list item into a trip to plan

### ISSUE THREAD

**Issue by dunkl1lm** [dunkl1lm/Planit_Earth#8]
### User Story
When I decide to go somewhere from my bucket list, I'd like to convert the destination to a planned trip.

### Acceptance Criteria
- [ ] confirmation to transfer the task from the bucket list into a planned trip
- [ ] option to make the destination the entire trip, or just a destination as a part of the trip
- [ ] option to create the trip completely when I decide to convert, or just save the planned trip with the rest of the details blank
- [ ] remove the destination from the bucket list

### Task List
- [ ] mockup
- [ ] prototype
- [ ] database
- [ ] backend
- [ ] frontend
